### PR TITLE
Fix main property in bower.json

### PR DESCRIPTION
**Pull request by zckrs**
That should fix issue with Wiredep.

### CODE REVIEW

**Comment by kane-c** [comment]
Thanks :+1:

**Comment by zckrs** [comment]
Np. Will you publish a new version soon ?

**Comment by kane-c** [comment]
Done :)

**Comment by maxmx** [comment]
@kane-c can you register an npm user, or share your current one, I'll add you as an owner on the npm package so that you can `npm publish` new versions.

Also bower is forgiving when republishing releases (ie. deleting 4.0.3 and recreating it) but npm is not, hence why I had to increment the release in 955468a06afb574ff3d75d66819a89cde68a41e5, then run `npm publish`.

**Comment by kane-c** [comment]
@maxmx Sorry, I didn't know that. I haven't done a great deal of work with Bower or npm. My username on npm is the same as here - kane-c.

Thanks for the info on releasing; I'll be sure to do that next time.

**Comment by maxmx** [comment]
@kane-c, I added you as an owner of the NPM repo.

Steps to release:

* Update package.json and bower.json, push to master
* From github UI you can create the release.
* From your cli, pull the latest master and run `npm publish` for NPM.
* Bower just takes care of itself.

**Pull request merged**
