### PR TITLE
Upgrade Bootstrap to v3.3.4

### PR DESCRIPTION
**Pull request by kane-c**
Also fixes mistake in some comments, a bug in panel tables, and a regression caused by #90.

This also bumps the package version to 4.0.3 (not sure what versioning we are going for, feel free to change if necessary)

### CODE REVIEW

**Comment by fruchtose** [comment]
Your work is very much appreciated! :+1: Just curious, are you doing all of the Stylus conversion by hand?

**Comment by kane-c** [comment]
Thanks for your support :)

I used a Less to Stylus converter like [this](https://gist.github.com/MoOx/3490671) and [this](https://github.com/andreypopp/less2stylus) that I tweaked a bit back when I did BS 3.1 or so. I then cleaned it up by hand (the Less version isn't 100% neat).

Since then, I've been doing it by hand using `git diff` between the releases of the Less version of Bootstrap and just applying all the changes to the Stylus version.

Doesn't take too long any more. Having said that, if you know of a better way or any other tools, I'm all ears!

ps Check out [font-awesome-stylus](https://github.com/raulghm/Font-Awesome-Stylus) for more Stylus goodness!

**Comment by fruchtose** [comment]
Thanks for the explanation. If anything the fact that you do it manually with diffs makes me very grateful for your work.

**Comment by maxmx** [comment]
Yeah thanks @kane-c for continuing this, I remember doing the first 2-3 versions all by hand and I probably would have stopped if it weren't for you.

**Comment by kane-c** [comment]
@maxmx Thanks :) Happy to help. Stylus is great (such clean syntax!) - I wish it was more popular.

**Pull request merged**
